// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTiu_5V2DzMJSiTXBeb7sGTVVhH_GNFk',
    appId: '1:265918086380:web:891e76e86cd39a48acf9c9',
    messagingSenderId: '265918086380',
    projectId: 'first-notification-3c499',
    authDomain: 'first-notification-3c499.firebaseapp.com',
    storageBucket: 'first-notification-3c499.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChOLUpxPNxj96LTt3jpkPIjbzrp7Va71E',
    appId: '1:265918086380:android:9d8d7d7c69f684edacf9c9',
    messagingSenderId: '265918086380',
    projectId: 'first-notification-3c499',
    storageBucket: 'first-notification-3c499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD23pw1l5wVEQfZRzXrozxI2oZ_SCUpG4A',
    appId: '1:265918086380:ios:5cecf0f57888d687acf9c9',
    messagingSenderId: '265918086380',
    projectId: 'first-notification-3c499',
    storageBucket: 'first-notification-3c499.appspot.com',
    iosClientId: '265918086380-9859ml2sln61bahmv7ogumsp6qq60a5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApplicationMazenMomen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD23pw1l5wVEQfZRzXrozxI2oZ_SCUpG4A',
    appId: '1:265918086380:ios:5d2f870732384b13acf9c9',
    messagingSenderId: '265918086380',
    projectId: 'first-notification-3c499',
    storageBucket: 'first-notification-3c499.appspot.com',
    iosClientId: '265918086380-srg31b5k99rrg2uf7r5ahn9d08adcq6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApplicationMazenMomen.RunnerTests',
  );
}
